title: indra's webpage
description: Programming Snippets, Data Viz, and Scientific Computing
name: Indranil Roy
github_username: indranil-sscu

theme: minima

minima:
  navigation:
    - title: "Home"
      url: "/"
    - title: "Posts"
      url: "/posts/"
    - title: "Personal Site"
      url: "http://sites.google.com/iisc.ac.in/indranilroy/"