title: indra's webpage
description: Programming Snippets, Data Viz, and Scientific Computing
theme: minima

minima:
  navigation:
    - title: "Home"
      url: "/"
    - title: "Posts"
      url: "/posts/"